# Generated by Django 5.0.1 on 2026-02-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('text', 'Plain Text'), ('html', 'HTML')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='bcc_emails',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='body_sent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='cc_emails',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
